name: Dockerhub publish
on: [ push ]
jobs:
  Push-To-Dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: "jre8-flyway-alpine"
